	echo "test/qwer.rt"
	./miniRT test/qwer.rt
	echo "test/asdf.rt"
	./miniRT test/asdf.rt
	echo "test/test_AA.rt"
	./miniRT test/test_AA.rt
	echo "test/test_CC.rt"
	./miniRT test/test_CC.rt
	echo "test/test_LL.rt"
	./miniRT test/test_LL.rt
	echo "test/testA.rt"
	./miniRT test/testA.rt
	echo "test/testC.rt"
	./miniRT test/testC.rt
	echo "test/testL.rt"
	./miniRT test/testL.rt
	echo "test/test_none.rt"
	./miniRT test/test_none.rt
	echo "test/test.rt"
	./miniRT test/test.rt
	echo "test/testAw.rt"
	./miniRT test/testAw.rt
	echo "test/testCw.rt"
	./miniRT test/testCw.rt
	echo "test/testLw.rt"
	./miniRT test/testLw.rt